// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3AzzxUMG8gRNbZ5t6dE9VXjvnxQ6o-ZQ',
    appId: '1:997708011154:web:843970e6533e84b5aef84b',
    messagingSenderId: '997708011154',
    projectId: 'pagaria-application',
    authDomain: 'pagaria-application.firebaseapp.com',
    storageBucket: 'pagaria-application.appspot.com',
    measurementId: 'G-PZ4S5TPSPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANdipyxlywQd-0xSjCKSmTAwhGsQcPG40',
    appId: '1:997708011154:android:87db5d49122f5a68aef84b',
    messagingSenderId: '997708011154',
    projectId: 'pagaria-application',
    storageBucket: 'pagaria-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSKlzn2LQD0MzPPnAhWxM5UksWVcicz_4',
    appId: '1:997708011154:ios:b4929ad69b56614caef84b',
    messagingSenderId: '997708011154',
    projectId: 'pagaria-application',
    storageBucket: 'pagaria-application.appspot.com',
    iosBundleId: 'com.webnsoft.solution.webnsoftSolution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSKlzn2LQD0MzPPnAhWxM5UksWVcicz_4',
    appId: '1:997708011154:ios:7adb52a037c888e7aef84b',
    messagingSenderId: '997708011154',
    projectId: 'pagaria-application',
    storageBucket: 'pagaria-application.appspot.com',
    iosBundleId: 'com.webnsoft.solution.webnsoftSolution.RunnerTests',
  );
}
